### ISSUE TITLE
fails to run on android device

### ISSUE THREAD

**Issue by ghost** [neohelden/Flutter-AdaptiveCards#16] opened 2019-06-16 09:54 UTC
cd /Users/apple/workspace/go/src/github.com/neohelden/Flutter-AdaptiveCards/example && flutter run -d all
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...                                              2.7s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process
"/Users/apple/workspace/go/src/github.com/neohelden/Flutter-AdaptiveCards/example/android/gradl
ew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file
'/Users/apple/workspace/go/src/github.com/neohelden/Flutter-AdaptiveCards/example/android/app/b
uild.gradle' line: 55

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get
more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command:
  /Users/apple/workspace/go/src/github.com/neohelden/Flutter-AdaptiveCards/example/android/grad
  lew app:properties

Please review your Gradle project setup in the android/ folder.

----

x-MacBook-Pro:cards apple$ flutter doctor -v
[✓] Flutter (Channel master, v1.7.5-pre.12, on Mac OS X 10.14.5 18F132, locale en-DE)
    • Flutter version 1.7.5-pre.12 at /Users/apple/fvm/master
    • Framework revision 07dc236237 (3 hours ago), 2019-06-16 19:18:39 +1200
    • Engine revision f44b7b5662
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • Nexus 5X • 024e140e5e46c929 • android-arm64 • Android 8.1.0 (API 27)

**Comment by Norbert515** [comment] 2019-06-17 08:56
I suppose this is because I used a relative path for the adaptive card dependency. I changed it to a GitHub dependency now, I _should_ work now!

**Comment by gedw99** [comment] 2019-06-17 09:11
tested with android emulator - still same error unfortunately
Why not just rerun the flutter create.

**Comment by Norbert515** [comment] 2019-06-17 10:13
Ok the problem seems to be this line
```
            storeFile file(keystoreProperties['storeFile'])
```
Because we haven't checked in our keystore it can't find the keystore path.

Have you tried to run the app in debug/ profile mode?

**Comment by gedw99** [comment] 2019-06-30 17:14
sorry forgot to come back to this.

flutter run --debug -d all

same error..

````

flutter run --debug -d all
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...                                              1.9s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process
"/Users/apple/workspace/go/src/github.com/neohelden/Flutter-AdaptiveCards/example/android/gradlew"
exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file
'/Users/apple/workspace/go/src/github.com/neohelden/Flutter-AdaptiveCards/example/android/app/build.g
radle' line: 55

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more
log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command:
  /Users/apple/workspace/go/src/github.com/neohelden/Flutter-AdaptiveCards/example/android/gradlew
  app:properties


Please review your Gradle project setup in the android/ folder.

````

**Comment by Norbert515** [comment] 2019-07-12 10:49
Does removing said line work?

**Comment by beevelop** [comment] 2020-05-18 09:02
This issue was caused by the signing configuration in Gradle. As it is no longer enforced / required for the Example app, this issue should be solved.

**Closed by beevelop** 2020-05-18 09:02 UTC
